person:
  userName: zhangsan
  boss: true
  birth: 2019/12/9
  age: 30
  interests: [篮球,足球]
  animal: [猫猫,狗狗]
  score: {english: 80,math: 90}
  salarys: [999.9,999]
  pet:
    name: miaomiao
    weight: 12.5
  allPets:
    sick:
      - {name: gougou,weigth: 10.5}
      - name: maomao
        weight: 9.9
      - name: chongchong
        weight: 7.7
    health: [{name: ahua,weight: 8.8},{name: ahong,weigth: 10.5}]